# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Musical meets Maastricht
logo: "/assets/images/logo4.png"
email: musicalmeetsmaastricht@googlegroups.com
description: >- # this means to ignore newlines until "baseurl:"

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Musical meets Maastricht"
  avatar : "/assets/images/logo4.png"
  bio    : "Lets bring the magic of musicals on the stages of Maastricht together."
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/AUBGcurious/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "musicalmeetsmaastricht@googlegroups.com"
    - label: "Producer's email"
      icon: "fas fa-fw fa-envelope-square"
      url: "laura@schellerup.com" 
    - label: "Producer's Whatsapp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/qr/WGHR577IP4M7I1"
    - label: "Producer's Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/laura_schellerup"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/AUBGcurious/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "musicalmeetsmaastricht@googlegroups.com"
    - label: "Producer's email"
      icon: "fas fa-fw fa-envelope-square"
      url: "laura@schellerup.com" 
    - label: "Producer's Whatsapp"
      icon: "fab fa-fw fa-whatsapp"
      url: "https://wa.me/qr/WGHR577IP4M7I1"
    - label: "Producer's Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/laura_schellerup"

defaults:
  #_portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: false
      related: false
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
